<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><Compile Include="PassiveParameterTests.cs"/><Compile Include="../Altium17-PartSearch/PartSearch/PassiveParameters.cs" Link="PassiveParameters.cs"/></ItemGroup></Project>
